laika.title = "YFinance4s"

laika.navigationOrder = [
  index.md
  charts.md
  options.md
  holders.md
  financials.md
  analysts.md
  sectors.md
  industries.md
  markets.md
  calendars.md
  search.md
  screener.md
  batch-operations.md
  reference.md
]
